name: lint and test with deno
on:
  push:
    paths:
      - "**/*.js"
      - "deno.*"
  pull_request:
    paths:
      - "**/*.js"
jobs:
  testingWithDeno:
    runs-on: ubuntu-latest
    steps:
      - name: Working version
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.30
      - name: Fuentes
        uses: actions/checkout@v3
      - name: Lint
        run: deno task lint
      - name: test
        run: deno task test
